In [91]:
import numpy as np
import pandas as pd
import sklearn

In [92]:
df = pd.read_csv("/content/breast-cancer.csv")
df.sample(4)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
389     90312         M        19.55         23.21          128.90     1174.0   
436    908916         B        12.87         19.54           82.67      509.2   
199    877500         M        14.45         20.22           94.49      642.7   
132  86730502         M        16.16         21.54          106.20      809.8   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
389          0.10100           0.13180         0.18560              0.10210   
436          0.09136           0.07883         0.01797              0.02090   
199          0.09872           0.12060         0.11800              0.05980   
132          0.10080           0.12840         0.10430              0.05613   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
389  ...          30.44           142.00      1313.0            0.1251   
436  ...          24.38            95.14       626.9            0.1214   
199  ...          30.12           117.90      1044.0            0.1552   
132  ...          31.68           129.70      1175.0            0.1395   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
389             0.2414          0.38290               0.18250          0.2576   
436             0.1652          0.07127               0.06384          0.3313   
199             0.4056          0.49670               0.18380          0.4753   
132             0.3055          0.29920               0.13120          0.3480   

     fractal_dimension_worst  Unnamed: 32  
389                  0.07602          NaN  
436                  0.07735          NaN  
199                  0.10130          NaN  
132                  0.07619          NaN  

[4 rows x 33 columns]

In [93]:
df = df.drop(["id","Unnamed: 32"],  axis = 1)
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [94]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [95]:
df.shape

(569, 31)

In [96]:
df["diagnosis"] = df["diagnosis"].map({'M':0,'B':1}).astype(int)
df["diagnosis"].sample(2)

482    1
535    0
Name: diagnosis, dtype: int64

In [97]:
X = df.iloc[ : , 1 :]
y = df.iloc[ : , 0]

In [98]:
df['diagnosis'].value_counts()

diagnosis
1    357
0    212
Name: count, dtype: int64

In [99]:
df.sample(3)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
59           1        8.618         11.79           54.34      224.5   
194          0       14.860         23.21          100.40      671.4   
77           0       18.050         16.15          120.20     1006.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
59           0.09752           0.05272         0.02061             0.007799   
194          0.10440           0.19800         0.16970             0.088780   
77           0.10650           0.21460         0.16840             0.108000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
59          0.1683  ...         9.507          15.40             59.9   
194         0.1737  ...        16.080          27.78            118.6   
77          0.2152  ...        22.390          18.91            150.1   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
59        274.9            0.1733             0.1239           0.1168   
194       784.7            0.1316             0.4648           0.4589   
77       1610.0            0.1478             0.5634           0.3786   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
59                0.04419          0.3220                  0.09026  
194               0.17270          0.3000                  0.08701  
77                0.21020          0.3751                  0.11080  

[3 rows x 31 columns]

In [100]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [101]:
X_train.sample(4)

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
234        9.567         15.91           60.21      279.6          0.08464   
129       19.790         25.12          130.40     1192.0          0.10150   
179       12.810         13.06           81.29      508.8          0.08739   
134       18.450         21.91          120.20     1075.0          0.09430   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
234           0.04087        0.016520              0.01667         0.1551   
129           0.15890        0.254500              0.11490         0.2202   
179           0.03774        0.009193              0.01330         0.1466   
134           0.09709        0.115300              0.06847         0.1692   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
234                 0.06403  ...         10.51          19.16   
129                 0.06113  ...         22.63          33.58   
179                 0.06133  ...         13.63          16.15   
134                 0.05727  ...         22.52          31.39   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
234            65.74       335.9            0.1504            0.09515   
129           148.70      1589.0            0.1275            0.38610   
179            86.70       570.7            0.1162            0.05445   
134           145.60      1590.0            0.1465            0.22750   

     concavity_worst  concave points_worst  symmetry_worst  \
234          0.07161               0.07222          0.2757   
129          0.56730               0.17320          0.3305   
179          0.02758               0.03990          0.1783   
134          0.39650               0.13790          0.3109   

     fractal_dimension_worst  
234                  0.08178  
129                  0.08465  
179                  0.07319  
134                  0.07610  

[4 rows x 30 columns]

In [102]:
from sklearn.neighbors import KNeighborsClassifier
reg = KNeighborsClassifier()
reg.fit(X_train,y_train)

KNeighborsClassifier()

In [103]:
len(X_train),len(y_train)

(455, 455)

In [104]:
outcomes =reg.predict(X_train)
len(outcomes)

455

In [105]:
training_data = pd.DataFrame()
training_data = X_train.copy()
training_data["y_actual_values"]= y_train
training_data["y_actual_values_by_predict"]= outcomes

In [106]:
training_data.sample(10)

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
407        12.85         21.37           82.63      514.5          0.07551   
543        13.21         28.06           84.88      538.4          0.08671   
342        11.06         14.96           71.49      373.9          0.10330   
481        13.90         19.24           88.73      602.9          0.07991   
12         19.17         24.80          132.40     1123.0          0.09740   
490        12.25         22.44           78.18      466.5          0.08192   
236        23.21         26.97          153.50     1670.0          0.09509   
366        20.20         26.83          133.70     1234.0          0.09905   
389        19.55         23.21          128.90     1174.0          0.10100   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
407           0.08316         0.06126              0.01867         0.1580   
543           0.06877         0.02987              0.03275         0.1628   
342           0.09097         0.05397              0.03341         0.1776   
481           0.05326         0.02995              0.02070         0.1579   
12            0.24580         0.20650              0.11180         0.2397   
490           0.05200         0.01714              0.01261         0.1544   
236           0.16820         0.19500              0.12370         0.1909   
366           0.16690         0.16410              0.12650         0.1875   
389           0.13180         0.18560              0.10210         0.1989   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  perimeter_worst  area_worst  \
407                 0.06114  ...            91.63       645.8   
543                 0.05781  ...            92.48       629.6   
342                 0.06907  ...            79.76       440.0   
481                 0.05594  ...           104.40       830.5   
12                  0.07800  ...           151.70      1332.0   
490                 0.05976  ...            92.74       622.9   
236                 0.06309  ...           206.00      2944.0   
366                 0.06020  ...           160.00      1671.0   
389                 0.05884  ...           142.00      1313.0   
568                 0.05884  ...            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
407           0.09402            0.19360           0.1838   
543           0.10720            0.13810           0.1062   
342           0.14180            0.22100           0.2299   
481           0.10640            0.14150           0.1673   
12            0.10370            0.39030           0.3639   
490           0.12560            0.18040           0.1230   
236           0.14810            0.41260           0.5820   
366           0.12780            0.34160           0.3703   
389           0.12510            0.24140           0.3829   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  \
407               0.05601          0.2488                  0.08151   
543               0.07958          0.2473                  0.06443   
342               0.10750          0.3301                  0.09080   
481               0.08150          0.2356                  0.07603   
12                0.17670          0.3176                  0.10230   
490               0.06335          0.3100                  0.08203   
236               0.25930          0.3103                  0.08677   
366               0.21520          0.3271                  0.07632   
389               0.18250          0.2576                  0.07602   
568               0.00000          0.2871                  0.07039   

     y_actual_values  y_actual_values_by_predict  
407                1                           1  
543                1                 

In [107]:
tp = 0
tn = 0
fp = 0
fn = 0

for i in training_data.index:
  if training_data['y_actual_values'][i]==1 and training_data['y_actual_values_by_predict'][i]==1:
    tp = tp + 1
  elif training_data['y_actual_values'][i]==0 and training_data['y_actual_values_by_predict'][i]==0:
    tn = tn + 1
  elif training_data['y_actual_values'][i]==1 and training_data['y_actual_values_by_predict'][i]==0:
    fn = fn + 1
  else:
    fp  = fp + 1

print(f"true positive: {tp}")
print(f"true negative: {tn}")
print(f"false positive: {fp}")
print(f"false negavtive: {fn}")

true positive: 281
true negative: 147
false positive: 22
false negavtive: 5


In [108]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train,outcomes)

array([[147,  22],
       [  5, 281]])

In [109]:
(tp+tn) / (tp + tn+ fp + fn )

0.9406593406593406

In [110]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,outcomes)

0.9406593406593406

In [111]:
from  sklearn.metrics import classification_report
print(classification_report(y_train,outcomes))

              precision    recall  f1-score   support

           0       0.97      0.87      0.92       169
           1       0.93      0.98      0.95       286

    accuracy                           0.94       455
   macro avg       0.95      0.93      0.94       455
weighted avg       0.94      0.94      0.94       455



In [112]:
print(f"classification report:{classification_report(y_train,outcomes)}")

classification report:              precision    recall  f1-score   support

           0       0.97      0.87      0.92       169
           1       0.93      0.98      0.95       286

    accuracy                           0.94       455
   macro avg       0.95      0.93      0.94       455
weighted avg       0.94      0.94      0.94       455



In [113]:
len(X_test)

114

In [114]:
prediction = reg.predict(X_test)
len(prediction)

114

In [115]:
y_test.value_counts()

diagnosis
1    71
0    43
Name: count, dtype: int64

In [116]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,prediction)

array([[38,  5],
       [ 0, 71]])

In [117]:
accuracy_score(y_test,prediction)

0.956140350877193

In [118]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       1.00      0.88      0.94        43
           1       0.93      1.00      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.94      0.95       114
weighted avg       0.96      0.96      0.96       114



In [119]:
k_values =  np.arange(3,50,2)
print(k_values)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


In [120]:
test_accuracy = []

for i in k_values:
  reg=KNeighborsClassifier(n_neighbors = i)
  reg.fit(X_train,y_train)
  test_accuracy.append(accuracy_score(y_test,reg.predict(X_test)))

print(test_accuracy)


[0.9298245614035088, 0.956140350877193, 0.956140350877193, 0.956140350877193, 0.9824561403508771, 0.9736842105263158, 0.9649122807017544, 0.9649122807017544, 0.9649122807017544, 0.9649122807017544, 0.956140350877193, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315]


In [121]:

max(test_accuracy)

0.9824561403508771

In [122]:
k_values[test_accuracy.index(max(test_accuracy))]

np.int64(11)

In [123]:
#k is 11 now

In [124]:
from sklearn.neighbors import KNeighborsClassifier
reg = KNeighborsClassifier()
reg.fit(X_test,y_test)

KNeighborsClassifier()

In [125]:
f = np.random.random((5,6)).ravel()
f

array([0.15441157, 0.60801012, 0.62270173, 0.98484267, 0.09356559,
       0.68591167, 0.71410545, 0.8461883 , 0.69255788, 0.68288889,
       0.99181618, 0.92609783, 0.03696571, 0.82489834, 0.46655443,
       0.28261342, 0.29711044, 0.8507283 , 0.21571101, 0.31965886,
       0.16137623, 0.32044592, 0.90024245, 0.27717149, 0.69620637,
       0.55651153, 0.64258098, 0.51602387, 0.58739565, 0.49746038])

In [126]:
import warnings
warnings.filterwarnings('ignore')

In [127]:
import warnings
warnings.filterwarnings("ignore")

In [128]:
if reg.predict([f])[0] == 0:
  print(f'Patient is Having **Malignin : {0}** Diagnosis')
else:
  print(f'Patient is Having **Benin : {1} ** Diagnosis')

Patient is Having **Benin : 1 ** Diagnosis
